### PR TITLE
Printing / GIF creation / Translation / other small features and changes

### PR DESCRIPTION
**Pull request by marcel-hofer**
First of all, thanks for your hard work making this project possible! It is just amazing :)

I made a few changes so that `photo-booth` better mets my own requirements.
All of these changes I made configurable (`on` / `off` or something like this) so that they could be merged back to your project without affecting existing setups.
I hope you and all other users of `photo-booth` can profit from these changes.

The first two changes were needed because I developed the other features on my Windows computer (and this was kind of a problem).
They are probably not best merged back but they won't harm anyone and provide a nice simulation mode ;)

## Detailed change list
- Added simulation mode (does not require a camera connection to run the application)
  - In this mode a red sample image will be generated with a black timestamp
  - New configuration value `gphoto2.simulate` which defaults to `false`
  - Added `gphoto2` dependency to `optionalDependencies` and `win32` to supported `os` list
- Removed symlink for photos folder and use virtual paths (express)
- Added GIF animation creation by multi selection of images inside the mobile application
  - New configuration value `webapp.gifDelay` which defaults to `1000`
  - Added `gif-encoder` and `get-pixels` to `dependencies`
- Added translation support with translations for EN / DE
  - Only the mobile application (without the settings page) has been translated
  - Translations are done by using [handlebarsjs](https://handlebarsjs.com/) (templating system)
  - New configuration value `language` which defaults to `en`
  - Added `handlebars`, `i18next` and `i18next-node-fs-backend` to `dependencies`
- Changed the mail address to a configurable *contact address*
  - Allows selecting one of the following address types: `none` / `email` / `text`
  - New configuration value `contactAddressType` which defaults to `email`
  - Changed name of textfile from `email-addresses.txt` to `contact-addresses.txt`
- Added blocking dialog for longer during actions in the mobile application
  - This shows the user that something is happening instead of no feedback after a button click
- Added printing support through mobile application
  - If printing is enabled, the full size image will be saved to a special directory (for printing in highest quality)
  - A new button inside the mobile application starts the print setup dialog which consists of the following steps:
    1. Layout selection: A preview of each available layout is shown and can be selected
    2. Photo selection: Based on the layout, multiple images for the layout placeholders can be selected
    3. Print preview: A print preview is generated and shown to the user. The user has the ability to change the photo selection or print the photo
    4. Print: The effective print action is being executed
  - If the simulation mode `printing.simulate` is enabled, the generated image only gets saved and not printed
  - Configurable layouts allow collage generation
    - Images will keep aspect ratio and are alligned center / middle of the available space
    - The image count for the layouts are not enforced (placeholders just don't get replaced)
    - Internally uses canvas library to create the collage
      Added `canvas` to `dependencies` (separate `package.json`).
      Needed to use seperate script execution (using process exec) due to something like a access violation which caused the electron application to crash.
      Therefore this additional installation step is now needed (see README.md):
      ```bash
      cd helpers/collage
      npm install
      ```
  - New configuration section:
    ```json
    "printing": {
        "enabled": false, // Shows the print button in the UI and enables the printing feature
        "printer": "printer-name", // The name of the printer to use
        "limitPerUser": 0, // Print limit per user, 0 = no limit, always no limit with the admin password
        "overlay": { // Optional overlay image configuration
          "image": "overlay.png", // Overlay image relative to application root
          "x": "right", // left / middle / right
          "y": "bottom" // top / middle / bottom
        },
        "grayscale": false, // Print in grayscale - seperate configuration to allow different app / print grayscale mode
        "layouts": [] // The available layouts
    }
    ```
    Where each layout can be defined like this:
    ```json
    {
        "key": "selphy_2x2", // Internal identifier
        "options": {
            "dpi": 300, // Printer quality (internal library uses 96 dpi - this is to ensure the best possible quality)
            "width": 2, // Images per row
            "height": 2, // Images per column
            "imageWidth": 868, // Maximal width of each image
            "imageHeight": 577, // Maximal height of each image
            "backgroundColor": "#ffffff", // Background color (is used to fill the spacing, the unused space when the original images do not have the same aspect ratio or placeholders without an image)
            "spacing": {
                "top": 8, // Top spacing
                "left": 0, // Left spacing
                "bottom": 8, // Bottom spacing
                "right": 1, // Right spacing
                "betweenImages": 11 // Spacing between images (top, right, bottom, left) - only relevant if more than 1 images
            }
        }
    }
    ```
  - The printing uses `cups` in the background for the communication with the printer
    - Successfully tested it with a `Canon Selphy CP1300` over USB
    - Additional installation steps needed (see new section in README.md)
  - Added `printer` to `optionalDependencies` (allows installation without printing dependencies)

### CODE REVIEW

**Comment by philipptrenz** [comment]
Hey @marcel-hofer thanks a lot for your great work! I will take a look at it asap!

**Comment by philipptrenz** [comment]
Hey @marcel-hofer, unfortunately I have too little time to devote myself to your features. So I'd like to offer you to join as a collaborator, as long as you have the time and inclination to incorporate your changes and react to related upcoming issues. If you are interested, please contact me personally 😉

**Comment by rawbertp** [comment]
Hi!

Thanks for the great work @philipptrenz & @marcel-hofer ! I'd love to see you as a contributor on this lovely project.

One question/request - do you think it would be possible to add some feature that allows the users to print the last series on button-press? I'm thinking of an actual photo-booth with two physical buttons, one for taking the photos (which is already there) and another one for printing. That would be awesome, wouldn't it? :-)

Cheers

**Comment by marcel-hofer** [comment]
Absolutely!

I also think of the possibility to have two buttons inside the webapp, one for taking a single picture and another for taking a series of four pictures.
The same I think could be useful when using push buttons and you don't have to change the config if you want to take an alternative count of pictures.

Because of this, I would go even further and make it more configurable. Something like this (example `config.json`):
```json
{
    "GPIO": {
        "enabled": true,
        "actions": [
            {
                "channel": 3, // First button will take one picture
                "action": "triggerPhoto" // Uses default series lenght of config.json
            },
            {
                "channel": 5, // Second button will take a series of 4 pictures
                "action": "triggerPhoto",
                "options": {
                    "photoSeriesLength": 4 // Other options (countdown length) already in config.json
                }
            },
            {
                "channel": 7, // Third button will print the last image taken (single image printout)
                "action": "print",
                "options": {
                    "layoutName": "selphy_1x1" // Configuration for single image printing layout
                }
            },
            {
                "channel": 8, // Fourth button will print the last four pictures
                "action": "print",
                "options": {
                    "layoutName": "selphy_2x2" // Configuration for a two by two printing layout
                }
            },
        ]
    }
}
```

This way the buttons will be highly customizable. I implemented this in a branch on my fork [`feature/configurable-gpio-shutter`](https://github.com/marcel-hofer/photo-booth/tree/feature/configurable-gpio-shutter) (based on `printing-gif-translations`).
Unfortunately I'm not able to test this using push buttons. I simulated it using the click event and it worked, but for testing the push buttons I need your help @rawbertp :)

Can you:
- Checkout my branch `feature/configurable-gpio-shutter`, do not change any configuration files and just test if it still works like before (backwards compatibility - should still trigger pictures)
- Change the settings, enable printing using a second button (see example above or in the README.md) and test the two buttons (trigger photo, printing) together
- *Hint*: You always can use the printing simulation mode

If everything works fine, I would create a pull request to merge this back to the main repository if @philipptrenz also likes this change.

**Comment by rawbertp** [comment]
@marcel-hofer Trying to test it now... However, not sure if my "fake-printer" setup is correct as it doesn't seem to work.

```json
	"printing": {
		"enabled": true,
		"simulate": true,
		"printer": "printer-name",
		"limitPerUser": 0,
		"grayscale": false,
		"layouts": []
	},
```

I tried it with the webapp. If I select a picture and click the print icon a modal window/overlay appears and says:

Print
Please select the template.
[Cancel]

I cannot select any template, not sure how to proceed from there...

**Comment by marcel-hofer** [comment]
@rawbertp The printing feature needs one or more layouts. The layouts define how the printed picture will be created (eg. only one image or multiple images per printout).
You also need such a configuration even if you only want to print a single image. This part is documented in a different section inside the `README.md` (*Install a printer* - *Configure the application*).

I am using a *Canon Selphy CP1300* and my configuration looks like this (note the `layoutName` for the `GPIO` action has the same value as the `key` of one of the templates):

```json
"GPIO": {
    "enabled": true,
    "actions": [
        {
            "channel": 3,
            "action": "triggerPhoto",
            "options": {
                "photoSeriesLength": 4
            }
        },
        {
            "channel": 5,
            "action": "print",
            "options": {
                "layoutName": "selphy_2x2"
            }
        }
    ]
},
"printing": {
	"enabled": true,
	"simulate": true,
	"printer": "Canon_SELPHY_CP1300",
	"limitPerUser": 3,
    "grayscale": false,
	"layouts": [
		{
			"key": "selphy_1x1",
			"options": {
				"dpi": 300,
				"width": 1,
				"height": 1,
				"imageWidth": 1746,
				"imageHeight": 1160,
				"backgroundColor": "#ffffff",
				"spacing": {
					"top": 10,
					"left": 1,
					"bottom": 11,
					"right": 1,
					"betweenImages": 0
				}
			}
		},
		{
			"key": "selphy_2x2",
			"options": {
				"dpi": 300,
				"width": 2,
				"height": 2,
				"imageWidth": 868,
				"imageHeight": 577,
				"backgroundColor": "#ffffff",
				"spacing": {
					"top": 8,
					"left": 0,
					"bottom": 8,
					"right": 1,
					"betweenImages": 11
				}
			}
		},
		{
			"key": "selphy_1x2",
			"options": {
				"dpi": 300,
				"width": 1,
				"height": 2,
				"imageWidth": 1181,
				"imageHeight": 784,
				"backgroundColor": "#ffffff",
				"spacing": {
					"top": 79,
					"left": 0,
					"bottom": 80,
					"right": 0,
					"betweenImages": 21
				}
			}
		}
	]
},
```

**Comment by rawbertp** [comment]
Thanks for that. I'm getting the following error now:

```console
Error: Command failed: node ./collage-process.js /home/pi/content/photos/tmp/selphy_1x1_e10ab5b48f3bd1392476980314e3a1fe.jpeg eyJkcGkiOjk2LCJ3aWR0aCI6MSwiaGVpZ2h0IjoxLCJpbWFnZVdpZHRoIjoxNzQ2LCJpbWFnZUhlaWdodCI6MTE2MCwiYmFja2dyb3VuZENvbG9yIjoiI2ZmZmZmZiIsInNwYWNpbmciOnsidG9wIjoxMCwibGVmdCI6MSwiYm90dG9tIjoxMSwicmlnaHQiOjEsImJldHdlZW5JbWFnZXMiOjB9fQ== eyJncmF5c2NhbGUiOmZhbHNlfQ== /home/pi/content/photos/tmp/selphy_1x1_20191102_19-03-31.jpeg
internal/modules/cjs/loader.js:803
    throw err;
    ^

Error: Cannot find module 'canvas'
Require stack:
- /home/pi/photo-booth-improved/helpers/collage/collage-process.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:800:15)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/photo-booth-improved/helpers/collage/collage-process.js:5:33)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1051:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/photo-booth-improved/helpers/collage/collage-process.js'
  ]
}

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

```bash
pi@raspberrypi:~/photo-booth-improved $ git remote -v
origin	https://github.com/marcel-hofer/photo-booth.git (fetch)
origin	https://github.com/marcel-hofer/photo-booth.git (push)
pi@raspberrypi:~/photo-booth-improved $ git branch
  develop
* feature/configurable-gpio-shutter
  master
pi@raspberrypi:~/photo-booth-improved $ git pull
Already up to date.
```

**Comment by marcel-hofer** [comment]
Using printers requires additional installation steps documented under *Install a printer* - *Install printer software*.

Looks like the dependencies for one of the required helpers are not installed. Try running:
```bash
cd helpers/collage
npm install
```

This additional step is required because electron failed when using the `canvas` module inside it's main process.

**Comment by rawbertp** [comment]
Yeah sorry mea culpa, I missed the `npm install` in `helpers/collage` dir.

Edit: Nevermind, despite copying all three `apt install` commands it appears the last one wasn't executed. Fixed it by running `sudo apt install libpango1.0-dev`.

**Comment by rawbertp** [comment]
Ok, so I finally got the printing feature to work. Something must have been messed up with that nodejs stuff (which is like a black box to me, not sure if I'm goint to like it anytime soon tbh!). So I did a new clone, fresh `npm install` and now it works, at least from the web page.

However, it doesn't work from within the app. Not sure if I'm getting it right how to use it properly? So when taking photos, at what stage should I be able to press the button and trigger the printing process?

**Comment by marcel-hofer** [comment]
The printing works like this:
1. Click on the print button
2. The first step is the layout selection where a preview of every available layout should be shown (eg. 3 preview images for the settings I posted before)
3. Select the desired layout, you will be automatically redirected to the next step
4. On the next step you can select the pictures you want to print. Therefore the pictures you already have taken should be shown.
5. Select as much pictures as your layout requires (you see the numbers at *Number of selected images x / y*)
6. A new button *Show preview* should appear after you selected at last one picture - click on it to continue
7. On the next step you should see a preview of the printout (eg. the selected layout with the selected pictures)
   I added this step to not waste printouts if the user does not agree with the preview (he can go back and select different pictures or a different layout)
8. If you click on the *Print* button the effective print should be started
   - Then the image will be created and saved to the `hq` folder under the configured `content` directory.
   - This image will then be sent to the printer (only if `simulate = false`)

I see the process (installation / configuration / usage) is not self-explanatory. I gladly accept suggestions for improvement :)

**Comment by rawbertp** [comment]
I followed these instructions and it worked using the web page.

I was under the impression that you can trigger a print from the (Electron) app as well? I might be wrong, though...?!

**Comment by marcel-hofer** [comment]
Sorry, you can't trigger a print from the electron app at the moment. Only from within the web app.

I don't know a good way how we can add additional command buttons to the electron app while still being able to support the live-view / slideshow / click to trigger / ...

**Comment by DickesHortKind** [comment]
Hi, 

thanks for this great work. This software is awesome! 

Is there a possibilty to set up a overlay for each layout ? In the actual configuration one overlay is used for all layouts but this one is only shown in the first preview (after press print in web and choose layout).

BR

**Comment by marcel-hofer** [comment]
Currently not. For now, the same overlay is used for all print layouts.
I definitely want to support different overlays for each layout but this will be in printing v2.
For now I focus on finishing this pull request before I continue on additional features (timeline: end of this month).

Can you tell me more about your specific needs? I think I'll implement it so that the overlay can be overwritten per layout (each individual property `image` / `x` / `y`).
```json
{
    "printing": {
        ...,
        "overlay": {
            "image": "overlay.png",
            "x": "right",
            "y": "bottom"
        },
        "layouts": [
            {
                "key": "abc",
                "options": {
                    ...,
                    "overlay": { // Setting "overlay" to false will disable the overlay for this layout (if global configuration exists)
                        // "image" will fallback to overlay.png
                        "x": "left",
                        "y": "top"
                    },
                }
            }
        ]
	},
}
```

And what do you mean with *but this one is only shown in the first preview*? The overlay should be placed on all layouts (preview and printing but not for the layout selection).
I have a configuration of 3 layouts and it works like it should. The only thing missing is the ability to change the overlay for each layout - isn't it?

**Comment by DickesHortKind** [comment]
Hello, that's exactly how I would suggest the solution. That you can set an overlay for every layout, as in your example. 

I just thought that maybe it already works with a special configuration in "layouts".

It's completely okay if you want to complete this feature first.

The topic with the preview is done. The problem was that after changing the overlay, the preview did not change. Only after I changed the layout (Example: set to new value -> "backgroundColor":"# fff000") did the correct preview come back. 
The preview will probably only be updated when the parameters in the layout change.

For me, this is not a problem.

Thank you.

**Comment by marcel-hofer** [comment]
I will merge this pull request in it's current state.

As mentioned in the comments, there is still potential for improvement, but nothing really critical. I will create issues to better keep track of them.

**Pull request merged**
