### PR TITLE
- Added LivePreview

### PR DESCRIPTION
**Pull request by lal12**

### CODE REVIEW

**Comment by lal12** [comment]
The way of displaying the live preview is not really efficient and sometimes has a short black flick. However it seems to need much less CPU ressources than reading the file into a NodeJS buffer.

**Comment by Tusubube** [comment]
Very useful, thanks !

**Comment by webworkerJoshua** [comment]
I'm struggling with this LivePreview: After the takePicture event my app restarts and there is no saved photo. Is there any way to really "close" the preview function? 
In general I'd really like this function to be included in the core.

**Comment by lal12** [comment]
> I'm struggling with this LivePreview: After the takePicture event my app restarts and there is no saved photo. Is there any way to really "close" the preview function?

Hmm, I didn't encountered this behaviour. I don't know what exactly you mean by "really closing" the preview. The preview works by retrieving a preview image every X ms (depending on the configured framerate), as just before a picture is taken that process of polling the camera for previews is stopped until the image is retrieved than it is started again.

There might be some issues with some camera models not perfectly supporting previews or having troubles with high framerates.

- Do you run this project under windows? I assumed it is an linux only project, so my code won't work on a windows system.
- Which camera model do you tried?
- Try to play around with the framerate config, maybe apply a very low one (like 1 or 2)
- You also could try to stop the preview a bit earlier during the countdown. For that you have to move `if(livePreview)
livePreview.stop();` from line 136+137 above line 133 (in file "booth.js").

**Comment by webworkerJoshua** [comment]
Sorry that I haven't answered yet, had a busy time. I now tried with a fresh git clone of your PR and it seams to work now. I don't know what the difference was. 
So thanks alot for your integration! :-)

**Comment by philipptrenz** [comment]
Hey, thanks for your work @lal12 and thanks for the testing @blaueQuelle!

On which hardware did you two test? As the Raspberry Pi is still the main used platform for the project, I'd like to have this feature auto-disabled for the Pi in case that the performance requirements are too high for it.

**Comment by webworkerJoshua** [comment]
I'm currently testing at a Mac, but as I'm finished adding my modifications (watermark, stylings), I'll load it to a Raspberry Pi 3 and test it there again.
When there is no `live` setting in my.config.json, no LivePreview is loaded. So by default performance at a RPi should be fine

**Comment by philipptrenz** [comment]
Yeah, I understand!
If the performance on the Pi is not enough, I would like to disable the live preview per-code on this hardware to prevent issues about the poor performance on the Pi.

Since I'm willing to merge the pull request very soon, but even in the near future will not come to testing, I would be glad if you could give me feedback on the performance of the feature on the Pi 3 😉

**Comment by lal12** [comment]
I will also use this on a SBC (probably a PI 3B+) in the next weeks. But I did not test the performance on it yet. However I am pretty sure, that at least at lower framerates it will handle it, maybe with a relatively high CPU utilization.

**Comment by webworkerJoshua** [comment]
I've tested it now at a RPi 3B+ (& Nikon D7100) on a fresh raspbian stretch with LivePreview framerate set to 10. During the countdown and LivePreview the CPU has about 75% workload and it's working smooth enough. I also added a "flash" (full white page) when the countdown finishes - still working smooth.
From my point of view: ready to merge

**Comment by blaueQuelle** [comment]
I'll try to add the flash to a separate PR if anyone else is interested ;-)

**Comment by webworkerJoshua** [comment]
So, after "battle-testing" the photo-booth for 3 evenings with each around 150 pictures I definetely can say that the LivePreview is performing well on a RPi 3 B+

**Comment by philipptrenz** [comment]
Thanks a lot @blaueQuelle! Also for your 'flash' PR (had that also in mind for a while now). I'll merge both into the master.

**Pull request merged**
